repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: debug-statements
    - id: detect-private-key
    - id: requirements-txt-fixer
    - id: check-toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
    - id: ruff
      args:
      - --fix
      - --exit-non-zero-on-fix
    - id: ruff-format
