site_name: Wordly

nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md

theme:
  name: "material"
  palette:
    primary: deep purple
    accent: yellow

plugins:
  - mkdocstrings

